import type { Distribution, DistributionDetail } from "../models";

/**
 * Mock data for distributions - represents the main distribution records
 */
export const distributions: Distribution[] = [
  {
    id: 'dst--001',
    region: 'West Nile',
    date: '2025-06-15',
    status: 'Planned',
    beneficiaries: 1000,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
  {
    id: 'dst--002',
    region: 'Eastern Province',
    date: '2025-06-10',
    status: 'Completed',
    beneficiaries: 850,
    aidType: 'Medical',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--003',
    region: 'Northern Region',
    date: '2025-07-01',
    status: 'Ongoing',
    beneficiaries: 950,
    aidType: 'Shelter',
    deliveryChannel: 'Mobile Units',
  },
  {
    id: 'dst--004',
    region: 'Central District',
    date: '2025-06-20',
    status: 'Planned',
    beneficiaries: 600,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--005',
    region: 'Southern Plains',
    date: '2025-07-10',
    status: 'Completed',
    beneficiaries: 1300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
  {
    id: 'dst--006',
    region: 'Lake Zone',
    date: '2025-06-25',
    status: 'Ongoing',
    beneficiaries: 700,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
  },
  {
    id: 'dst--007',
    region: 'Highland Area',
    date: '2025-07-05',
    status: 'Planned',
    beneficiaries: 400,
    aidType: 'Education',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--008',
    region: 'Coastal Belt',
    date: '2025-06-30',
    status: 'Completed',
    beneficiaries: 1100,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
  {
    id: 'dst--009',
    region: 'River Valley',
    date: '2025-07-12',
    status: 'Ongoing',
    beneficiaries: 500,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--010',
    region: 'Urban Center',
    date: '2025-07-15',
    status: 'Planned',
    beneficiaries: 2000,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
  },
  {
    id: 'dst--011',
    region: 'Mountain Region',
    date: '2025-07-18',
    status: 'Completed',
    beneficiaries: 750,
    aidType: 'Shelter',
    deliveryChannel: 'Direct Distribution',
  },
  {
    id: 'dst--012',
    region: 'Desert Fringe',
    date: '2025-07-20',
    status: 'Ongoing',
    beneficiaries: 300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
  },
];

/**
 * Mock data for detailed distribution information including beneficiary lists
 */
export const distributionDetails: Record<string, DistributionDetail> = {
  'dst--001': {
    id: 'dst--001',
    region: 'West Nile',
    date: '2025-06-15',
    status: 'Planned',
    beneficiaries: 1000,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--001', name: 'Jane Doe' },
      { id: 'bnf--002', name: 'John Smith' },
      { id: 'bnf--003', name: 'Alice Brown' },
      { id: 'bnf--004', name: 'Bob White' },
    ],
  },
  'dst--002': {
    id: 'dst--002',
    region: 'Eastern Province',
    date: '2025-06-10',
    status: 'Completed',
    beneficiaries: 850,
    aidType: 'Medical',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--005', name: 'Carlos Green' },
      { id: 'bnf--006', name: 'Fatima Noor' },
      { id: 'bnf--007', name: 'Liam Chen' },
      { id: 'bnf--008', name: 'Sara Ahmed' },
    ],
  },
  'dst--003': {
    id: 'dst--003',
    region: 'Northern Region',
    date: '2025-07-01',
    status: 'Ongoing',
    beneficiaries: 950,
    aidType: 'Shelter',
    deliveryChannel: 'Mobile Units',
    beneficiaryList: [
      { id: 'bnf--009', name: 'Emily Davis' },
      { id: 'bnf--010', name: 'Mohammed Ali' },
      { id: 'bnf--011', name: 'Olga Petrova' },
      { id: 'bnf--012', name: 'Samuel Kim' },
    ],
  },
  'dst--004': {
    id: 'dst--004',
    region: 'Central District',
    date: '2025-06-20',
    status: 'Planned',
    beneficiaries: 600,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--013', name: 'Amina Yusuf' },
      { id: 'bnf--014', name: 'Lucas Rossi' },
      { id: 'bnf--015', name: 'Priya Singh' },
      { id: 'bnf--016', name: 'David Lee' },
    ],
  },
  'dst--005': {
    id: 'dst--005',
    region: 'Southern Plains',
    date: '2025-07-10',
    status: 'Completed',
    beneficiaries: 1300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--017', name: 'Maria Garcia' },
      { id: 'bnf--018', name: 'James Wilson' },
      { id: 'bnf--019', name: 'Chen Wei' },
      { id: 'bnf--020', name: 'Nia Johnson' },
    ],
  },
  'dst--006': {
    id: 'dst--006',
    region: 'Lake Zone',
    date: '2025-06-25',
    status: 'Ongoing',
    beneficiaries: 700,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
    beneficiaryList: [
      { id: 'bnf--021', name: 'Omar Farouk' },
      { id: 'bnf--022', name: 'Sophia Martinez' },
      { id: 'bnf--023', name: 'Ahmed Hassan' },
      { id: 'bnf--024', name: 'Julia Novak' },
    ],
  },
  'dst--007': {
    id: 'dst--007',
    region: 'Highland Area',
    date: '2025-07-05',
    status: 'Planned',
    beneficiaries: 400,
    aidType: 'Education',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--025', name: 'Elena Rodriguez' },
      { id: 'bnf--026', name: 'Thomas Anderson' },
      { id: 'bnf--027', name: 'Yuki Tanaka' },
      { id: 'bnf--028', name: 'Isabella Silva' },
    ],
  },
  'dst--008': {
    id: 'dst--008',
    region: 'Coastal Belt',
    date: '2025-06-30',
    status: 'Completed',
    beneficiaries: 1100,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--029', name: 'Marcus Johnson' },
      { id: 'bnf--030', name: 'Aisha Patel' },
      { id: 'bnf--031', name: 'Lucas Wang' },
      { id: 'bnf--032', name: 'Emma Thompson' },
    ],
  },
  'dst--009': {
    id: 'dst--009',
    region: 'River Valley',
    date: '2025-07-12',
    status: 'Ongoing',
    beneficiaries: 500,
    aidType: 'Water',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--033', name: 'Daniel Kim' },
      { id: 'bnf--034', name: 'Sofia Rodriguez' },
      { id: 'bnf--035', name: 'Alex Chen' },
      { id: 'bnf--036', name: 'Maya Patel' },
    ],
  },
  'dst--010': {
    id: 'dst--010',
    region: 'Urban Center',
    date: '2025-07-15',
    status: 'Planned',
    beneficiaries: 2000,
    aidType: 'Medical',
    deliveryChannel: 'Mobile Units',
    beneficiaryList: [
      { id: 'bnf--037', name: 'Ryan O\'Connor' },
      { id: 'bnf--038', name: 'Zara Khan' },
      { id: 'bnf--039', name: 'Noah Williams' },
      { id: 'bnf--040', name: 'Lily Zhang' },
    ],
  },
  'dst--011': {
    id: 'dst--011',
    region: 'Mountain Region',
    date: '2025-07-18',
    status: 'Completed',
    beneficiaries: 750,
    aidType: 'Shelter',
    deliveryChannel: 'Direct Distribution',
    beneficiaryList: [
      { id: 'bnf--041', name: 'Gabriel Santos' },
      { id: 'bnf--042', name: 'Chloe Brown' },
      { id: 'bnf--043', name: 'Ethan Davis' },
      { id: 'bnf--044', name: 'Ava Wilson' },
    ],
  },
  'dst--012': {
    id: 'dst--012',
    region: 'Desert Fringe',
    date: '2025-07-20',
    status: 'Ongoing',
    beneficiaries: 300,
    aidType: 'Food',
    deliveryChannel: 'Vouchers',
    beneficiaryList: [
      { id: 'bnf--045', name: 'Mason Taylor' },
      { id: 'bnf--046', name: 'Harper Garcia' },
      { id: 'bnf--047', name: 'Logan Martinez' },
      { id: 'bnf--048', name: 'Evelyn Anderson' },
    ],
  },
};
